# Generated by Django 5.1 on 2024-09-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ntoes',
            new_name='Notes',
        ),
    ]
